env:
  browser: true
  commonjs: true
  es2021: true
  # jest: true
extends: airbnb-base
overrides: []
plugins: [jest]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
#  "eqeqeq": "on",
  jest/no-disabled-tests: warn,
  jest/no-focused-tests: error,
  jest/no-identical-title: error,
  jest/prefer-to-have-length: warn,
  jest/valid-expect: error
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
