env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
plugins: [eslint-plugin-jest]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  jest/valid-expect: error
#  "eqeqeq": "on",
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
